### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph-gradle-plugin#1]
- [ ] fix unit test (in progress)
 - [ ] use ChangelogLoader (TODO: cherry-pick in 2.x)
 - [ ] add Travis CI support
 - [ ] prepare branch for 3.x
